### ISSUE TITLE
Found a solution to ai problem

### ISSUE THREAD

**Issue by The-mortal-phoenix** [PGamerX-Legacy/muser#1]
Before I start I might be wrong but here is why I think the translate feature in the ai module does not work I analyzed the source code of [Alexa-bot-api](https://github.com/NithishPravin/alexa-bot-api) and I think the translate feature of the google trans does not work properly if any of u want I can give u the modified source code that I'm working on

**Comment by pgamerxdev** [comment]
That's actually a good idea, I think we can start our own Alexa bot API! 
My exams are till 7th February and then we can work on the same.

**Comment by The-mortal-phoenix** [comment]
done here it is

**Comment by The-mortal-phoenix** [comment]
https://github.com/The-mortal-phoenix/alexa-reply-api

**Comment by pgamerxdev** [comment]
Pls publish it as an npm package and DM me, Thanks

**Comment by pgamerxdev** [comment]
I think I fixed it and might consider your api for another command! Thanks

**Comment by pgamerxdev** [comment]
Just gonna pin it for others to know - 
I will merge the latest branch into master really soon!
