### ISSUE TITLE
Feature Muser on Dotenv.org

### ISSUE THREAD

**Issue by motdotla** [PGamerX-Legacy/muser#51]
Hi 👋,

Muser looks very cool. We're starting to put together a list of up and coming pieces of software that are making use of https://github.com/dotenv-org/cli, and it looks like you are. Can we feature you sometime as part of that list?

**Comment by pgamerx** [comment]
Hi there @motdotla ,yes we do use dotenv(and the CLI too), and we won't mind being featured on any list. 

Thank you.

**Comment by motdotla** [comment]
Great 🏆
